### ISSUE TITLE
Route is not bound.

### ISSUE THREAD

**Issue by GonzaloGPF** [knuckleswtf/scribe#112]
- [x] **I confirm that I have read and attempted the tips in the [Troubleshooting Guide](https://scribe.readthedocs.io/en/latest/troubleshooting.html).**

**What happened?**
1. Migrating from mpociot/laravel-apidoc-generator to Scribe v1
2. I ran `php artisan scribe:generate --verbose`
3. I saw:
```
🔊 info Processed route: [GET] wiber/appraisals/{appraisal}
🚸 warning Skipping route: [PUT,PATCH] wiber/appraisals/{appraisal} - Exception encountered.

   LogicException 

  Route is not bound.

  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:440
    436▕         if (isset($this->parameters)) {
    437▕             return $this->parameters;
    438▕         }
    439▕ 
  ➜ 440▕         throw new LogicException('Route is not bound.');
    441▕     }
    442▕ 
    443▕     /**
    444▕      * Get the key / value list of original parameters for the route.
  1   vendor/laravel/framework/src/Illuminate/Routing/Route.php:385
      Illuminate\Routing\Route::parameters()
  2   vendor/tymon/jwt-auth/src/Http/Parser/RouteParams.php:36
      Illuminate\Routing\Route::parameter()
  3   vendor/tymon/jwt-auth/src/Http/Parser/Parser.php:91
      Tymon\JWTAuth\Http\Parser\RouteParams::parse()
  4   vendor/tymon/jwt-auth/src/JWT.php:184
      Tymon\JWTAuth\Http\Parser\Parser::parseToken()
  5   vendor/tymon/jwt-auth/src/JWT.php:166
      Tymon\JWTAuth\JWT::parseToken()
  6   vendor/tymon/jwt-auth/src/JWTGuard.php:78
      Tymon\JWTAuth\JWT::getToken()
  7   vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:307
      Tymon\JWTAuth\JWTGuard::user()
  8   app/Http/Requests/Wiber/AppraisalRequest.php:42
      Illuminate\Auth\AuthManager::__call()
  9   vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php:88
      App\Http\Requests\Wiber\AppraisalRequest::rules()
  10  vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php:88
      call_user_func_array()
  11  vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php:64
      Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::getRouteValidationRules()
  12  vendor/knuckleswtf/scribe/src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php:32
      Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::getBodyParametersFromFormRequest()
  13  vendor/knuckleswtf/scribe/src/Extracting/Generator.php:229
      Knuckles\Scribe\Extracting\Strategies\BodyParameters\GetFromFormRequest::__invoke()
  14  vendor/knuckleswtf/scribe/src/Extracting/Generator.php:162
      Knuckles\Scribe\Extracting\Generator::iterateThroughStrategies()
  15  vendor/knuckleswtf/scribe/src/Extracting/Generator.php:109
      Knuckles\Scribe\Extracting\Generator::fetchBodyParameters()
  16  vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:118
      Knuckles\Scribe\Extracting\Generator::processRoute()
  17  vendor/knuckleswtf/scribe/src/Commands/GenerateDocumentation.php:73
      Knuckles\Scribe\Commands\GenerateDocumentation::processRoutes()
  18  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
      Knuckles\Scribe\Commands\GenerateDocumentation::handle()
  19  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37
      call_user_func_array()
  20  vendor/laravel/framework/src/Illuminate/Container/Util.php:40
      Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
  21  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:95
      Illuminate\Container\Util::unwrapIfClosure()
  22  vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:39
      Illuminate\Container\BoundMethod::callBoundMethod()
  23  vendor/laravel/framework/src/Illuminate/Container/Container.php:596
      Illuminate\Container\BoundMethod::call()
  24  vendor/laravel/framework/src/Illuminate/Console/Command.php:136
      Illuminate\Container\Container::call()
  25  vendor/symfony/console/Command/Command.php:258
      Illuminate\Console\Command::execute()
  26  vendor/laravel/framework/src/Illuminate/Console/Command.php:121
      Symfony\Component\Console\Command\Command::run()
  27  vendor/symfony/console/Application.php:920
      Illuminate\Console\Command::run()
  28  vendor/symfony/console/Application.php:266
      Symfony\Component\Console\Application::doRunCommand()
  29  vendor/symfony/console/Application.php:142
      Symfony\Component\Console\Application::doRun()
  30  vendor/laravel/framework/src/Illuminate/Console/Application.php:93
      Symfony\Component\Console\Application::run()
  31  vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129
      Illuminate\Console\Application::run()
  32  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

instead of...

```
🔊 info Processed route: [PUT,PATCH] wiber/appraisals/{appraisal}
```

**My environment:**
 - PHP version (from `php -v`): 
```
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
```
 - Framework (Laravel/Lumen): Laravel
 - Laravel/Lumen version: 
```
name     : laravel/framework
descrip. : The Laravel Framework.
keywords : framework, laravel
versions : * v8.9.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://laravel.com
source   : [git] https://github.com/laravel/framework.git 8a6bf870bcfa1597e514a9c7ee6df44db98abb54
dist     : [zip] https://api.github.com/repos/laravel/framework/zipball/8a6bf870bcfa1597e514a9c7ee6df44db98abb54 8a6bf870bcfa1597e514a9c7ee6df44db98abb54
path     : /home/vagrant/code/ERP/vendor/laravel/framework
```
 - Scribe version: 
```
name     : knuckleswtf/scribe
descrip. : Generate API documentation for humans from your Laravel codebase.✍
keywords : api, dingo, documentation, laravel
versions : * 1.9.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : http://github.com/knuckleswtf/scribe
source   : [git] https://github.com/knuckleswtf/scribe.git 640af34d029a6a3a6498e1af613a3b5818bfb8b3
dist     : [zip] https://api.github.com/repos/knuckleswtf/scribe/zipball/640af34d029a6a3a6498e1af613a3b5818bfb8b3 640af34d029a6a3a6498e1af613a3b5818bfb8b3
path     : /home/vagrant/code/ERP/vendor/knuckleswtf/scribe
names    : knuckleswtf/scribe, mpociot/laravel-apidoc-generator
```

**My Scribe config (minus the comments):**
```
    'type' => 'static',
    'static' => [
        'output_path' => 'public/docs',
    ],
    'laravel' => [
        'add_routes' => true,
        'docs_url' => '/docs',
        'middleware' => [],
    ],
    'auth' => [
        'enabled' => true,
        'in' => 'bearer',
        'name' => 'token',
        'use_value' => env('SCRIBE_AUTH_KEY'),
        'placeholder' => '{YOUR_AUTH_KEY}',
        'extra_info' => 'You can retrieve your token by issuing a <b>login</b> request.',
    ],
    'intro_text' => <<<INTRO
Welcome to our API documentation!

<aside>As you scroll, you'll see code examples for working with the API in different programming languages in the dark area to the right (or as part of the content on mobile), and you can switch the programming language of the examples with the tabs in the top right (or from the nav menu at the top left on mobile).</aside>
INTRO
    ,
    'example_languages' => [
        'php',
        'javascript',
    ],
    'base_url' => null,
    'title' => null,
    'description' => '',
    'postman' => [
        'enabled' => true,
        'overrides' => [],
    ],
    'openapi' => [
        'enabled' => true,
        'overrides' => [],
    ],
    'default_group' => 'Endpoints',
    'logo' => public_path('images') . '/logo.png',
    'router' => 'laravel',
    'routes' => [
        [
            'match' => [
                'domains' => ['*'],
                'prefixes' => ['wiber/*'],
            ],
            'include' => [],
            'exclude' => [],
            'apply' => [
                'headers' => [
                    'Content-Type' => 'application/json',
                    'Accept' => 'application/json',
                    'Authorization' => 'Bearer {token}',
                ],
                'response_calls' => [
                    'methods' => ['GET'],
                    'config' => [
                        'app.env' => 'documentation',
                        'app.debug' => true,
                    ],
                    'cookies' => [ ],
                    'queryParams' => [],
                    'bodyParams' => [],
                ],
            ],
        ],
    ],
    'fractal' => [
        'serializer' => null,
    ],
    'faker_seed' => null,
    'strategies' => [
        'metadata' => [
            GetFromDocBlocks::class,
        ],
        'urlParameters' => [
            GetFromUrlParamTag::class,
        ],
        'queryParameters' => [
            GetFromQueryParamTag::class,
        ],
        'headers' => [
            GetFromRouteRules::class,
            GetFromHeaderTag::class,
        ],
        'bodyParameters' => [
            GetFromFormRequest::class,
            GetFromBodyParamTag::class,
        ],
        'responses' => [
            UseTransformerTags::class,
            UseResponseTag::class,
            UseResponseFileTag::class,
            UseApiResourceTags::class,
            ResponseCalls::class,
        ],
        'responseFields' => [
            GetFromResponseFieldTag::class,
        ],
    ],
    'routeMatcher' => RouteMatcher::class,
    'continue_without_database_transactions' => [],
```

**Additional info:**
I'm not sure how can Scribe get authenticated for fetching authed routes. Any tip?

Thanks!

**Comment by shalvah** [comment]
This looks like it has to do with the JWT Auth library you're using. I recommend you dig in some more. My guess is it's trying to retrieve the current route (`request()->route()`), which currently isn't set in that FormRequest strategy.

> I'm not sure how can Scribe get authenticated for fetching authed routes. Any tip?

Scribe uses the `auth.use_value` from your config. Try generating a key manually (`php artisan tinker` can help), then paste it in there.

**Comment by GonzaloGPF** [comment]
Thanks for reply,
You was rigth, its related with that JWT package, so I switched to Sanctum.
However, I keep having problems with Scribe and logged users.
I found this [reply](https://github.com/knuckleswtf/scribe/issues/30) from you, and thats is excatly what is happening here now.

I tried to use the proposed snipped for [ResponseCall](https://github.com/knuckleswtf/scribe/wiki/Helpful-strategies-(snippets)#authenticating-as-a-particular-user-for-response-calls) Strategy. 

Unfortunately It doesnt work for me, I dont know how to setup this to le Scribe set an authenticated User in this escenario.

My Strategy (extending **ResponseCalls**):
```
protected function prepareRequest(Route $route, array $rulesToApply, array $urlParams, array $bodyParams, array $queryParams, array $fileParams, array $headers)
{
    $request = parent::prepareRequest($route, $rulesToApply, $urlParams, $bodyParams, $queryParams, $fileParams, $headers);

    $token = User::where('email', 'admin@mail.com')->first()->tokens()->first();

    $request->headers->set('Authorization', "Bearer {$token}");

    return $request;
}
```
Is it possible to setup an authed user in the FormRequest?

Thanks!

**Comment by shalvah** [comment]
> Is it possible to setup an authed user in the FormRequest?

I don't really get this.

Meanwhile, I don't think ResponseCalls are your problem (at least, in the original issue). From the stack trace you posted (frame 9), the error happened in the FormRequest strategy. Like I said, it looks like the auth package tried to resolve a route and failed (understandable, since that strategy bypasses most of Laravel and calls the FormRequest's `rules()` method directly).

I've pushed a new change.where I set the route resolver before launching the FormRequest strategy (see https://github.com/knuckleswtf/scribe/commit/ff1356469a12d4a8c9e8ec4a0267059c20e6b28d). Try it and see if that solves your problem with the original auth package. It's on master though, so you'll have to change your composer requirement to `dev-master`.

**Comment by shalvah** [comment]
Did that help? @GonzaloGPF

**Comment by ncatanchin** [comment]
@shalvah - I have also been battling this issue of `Route is not bound`.

I updated to `v2.0.3` as I noticed you had made relevant changes (ie. ff13564) - but the problem remained.

This StackOverflow was helpful: https://stackoverflow.com/a/41650931/216427

Modifying `GetFromFormRequest` strategy:

```
                $formRequest->setRouteResolver(function () use ($route, $formRequest) {
                    return $route->bind($formRequest);
                });
```

Seems to have solved the problem.

A similar change had to be applied to `UseApiResourceTags`:

https://github.com/knuckleswtf/scribe/blob/7c64840fb5cf94a9bcc1793e6a8d1a689e65d241/src/Extracting/Strategies/Responses/UseApiResourceTags.php#L122

```
        $request = app(Request::class);
        $response = $resource->toResponse($request->setRouteResolver(function () use ($route, $request) {
            return $route->bind($request);
        }));
```

This problem was occurring for me in any `FormRequest` or `ApiResource` class that tried to inspect the `Request` for the purpose of modifying to validation rules or the API response.

**Comment by shalvah** [comment]
I see. Should be a simple fix then. You can send in a PR.

**Comment by shalvah** [comment]
Turns out your solution isn't really correct. 

```php
        $request = app(Request::class);
        $response = $resource->toResponse($request->setRouteResolver(function () use ($route, $request) {
            return $route->bind($request);
        }));
```
Simply binding an empty request like you suggest here doesn't work. `$request->route()` will return null when loading relations or things like that. Need to bind the request globally, as well as make sure it matches the current route (url/method). See https://github.com/knuckleswtf/scribe/commit/cb3fa1fa4c09447c65650a4ad7dff9e969f344c8
