### ISSUE TITLE
Required fields from rules() are not parsed into OpenAPI file

### ISSUE THREAD

**Issue by torgeros** [knuckleswtf/scribe#916]
### Scribe version

4.38.0

### PHP version

8.3.10 (cli)

### Framework

Laravel

### Framework version

10.48.20

### Scribe config

```ruby
base_url => "http://localhost:8000"
static.output_path => "scribe_docs"
```

### What happened?

I have `rules()` that should tag object members as `required`.

For the generated scribe html file, everything not-required is correctly tagged as *optional*.
However, the generated openapi.yaml does not set *required* for all fields that are not optional.

Interestingly, member of objects in objects do not seem to work, while members of objects in arrays do.

## Nested Object case (does not work)

This is a section of my rules function:

```php
public function rules(): array
{
    return [
        'whitelabel' => 'string',
        'isPreview' => 'boolean',

        'issuer.email' => 'required|email',
        'issuer.phone' => 'nullable|string'

        // more rules...
    ];
}
```

This is the generated (& rendered) OpenAPI document:

![image](https://github.com/user-attachments/assets/9a57da69-9f51-471a-a9e6-51f39d0ad4aa)

And this is what I would expect (I changed the openapi doc manually):

![image](https://github.com/user-attachments/assets/f8268a24-9c43-48bc-8d4e-b0933e59f07d)

## Array of Objects case (does work!)

`rules()` snippet:

```php
        'items.*.description' => 'string',
        'items.*.quantity' => 'required|numeric',
```

Generated OpenAPI doc:

![image](https://github.com/user-attachments/assets/ca7cbfaa-ad13-49cc-848f-98f54ebbe2ea)

### Docs

- [X] I've checked [the docs](https://scribe.knuckles.wtf/laravel), the [troubleshooting guide](https://scribe.knuckles.wtf/laravel/troubleshooting), and [existing issues](https://github.com/knuckleswtf/scribe/issues?q=is%3Aissue+), but I didn't find a solution

**Comment by shalvah** [comment]
I think that's fixed by https://github.com/knuckleswtf/scribe/pull/905. I'll try to tag a release soon.

**Comment by AryaSvitkona** [comment]
I'm not sure it I should create a new issue or just add the feedback here.

We are facing the same issue with the `required` rule in our form request, but the update to the latest version `4.39.0` did not solve the issue.

**Scribe version**
4.39.0

**PHP version**
8.3.8 (cli)

**Framework**
Laravel

**Framework version**
11.34.2

**Scribe config**
```php
'type' => 'external_static',

    // See https://scribe.knuckles.wtf/laravel/reference/config#theme for supported options
    'theme' => 'elements',
```

**Rules**
```php
public function rules(): array {
        return [
            'meta.creation-date' => ['required', new Iso8601()],
            'data.*.creation-date' => ['required', new Iso8601()],
        ];
    }
```

**Screenshot:**
![Screenshot 2025-01-13 at 10 59 59](https://github.com/user-attachments/assets/cbbea6ac-28f9-4662-9fae-4876df99f3e8)

**OpenAPI**
```YAML
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                meta:
                  type: object
                  description: ''
                  
                  nullable: false
                  properties:
                    creation-date:
                      type: string
                      description: ''
                      example: et
                      nullable: false
                   required: // Line is missing
                      - creation-date // Line is missing
                data:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      creation-date:
                        type: string
                        description: ''
                        example: magni
                        nullable: false
                    required:
                      - creation-date
      security: []
```

**Expected behaviour:**
Both properties are marked as required

I tried to understand the logic how a required parameter is extracted, set and written into the OpenAPI spec, but seems to be a little to complex.

**Comment by torgeros** [comment]
@AryaSvitkona There is an indentation error in your yaml

```plain
                  properties:
                    creation-date:
                      type: string
                      description: ''
                      example: et
                      nullable: false
    HERE           required: //missing
                      - creation-date
```

**Comment by AryaSvitkona** [comment]
@torgeros That may be true, but that line was added to point to the issue ;)
That's why the `//missing` was added.

**Comment by AryaSvitkona** [comment]
@shalvah can we reopen this issue or should I add a new one?

**Comment by shalvah** [comment]
Please open a new issue, thanks 🙏
